[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
tracing-subscriber = "0.3.19"
winit = "0.30.11"
anyhow = "1.0.98"
nalgebra = "0.33.2"

[profile.dev]
opt-level = 0   # No optimizations (default for dev)
debug = true 